name: kokoro
channels:
  - defaults
dependencies:
  - python==3.9
  - libstdcxx~=12.4.0 # Necessário para carregar o espeak corretamente
  - pip:
      - kokoro>=0.3.1
      - soundfile
      - misaki[en]